apiVersion: v1
kind: Pod
metadata:
  name: todo-rpc-pod
  labels:
    name: todo-rpc-pod
    app:  todo-rpc
spec:
  containers:
    - name: todo-app
      image: gcr.io/todo-list-902/todo_server:latest
      ports:
        - containerPort:  9090

