
apiVersion: v1
kind: Service
metadata:
  name: todo-rpc-service
  labels:
    name: todo-rpc-service
    app: todo-rpc
spec:
  selector:
    name: todo-rpc-pod
    app:  todo-rpc
  ports:
    - port: 9090
      targetPort: 9090
     