
apiVersion: v1
kind: Service
metadata:
  name: todo-service
  labels:
    name: todo-service
    app: todo-client
spec:
  type: LoadBalancer
  selector:
    name: todo-client-pod
    app:  todo-client
  ports:
    - port: 3000
      targetPort: 3000
     